### ISSUE TITLE
关于nuswide数据集的小问题~

### ISSUE THREAD

**Issue by yiyikkk** [TreezzZ/DSDH_PyTorch#1]
打扰一下，新手对于数据集的使用还不大懂~ 请问nuswide数据集下载了之后是里面5个4g的文件都要用到吗？还是只用到了那个1.86G的zip，解压用这个就好呢？您分享的nus-wide-21是论文里常用的，只包含21类的nus-wide的子数据集吗？

**Comment by TreezzZ** [comment]
上传的是只包含21类的子数据集。之前有其他做Hashing的作者用的是Matlab的.mat文件类型，我给转换成了Pytorch的数据格式保存。因为文件太大，百度云要分卷上传，每个卷最大4G。
你要是使用的话所有文件都要下载，保存在一个文件夹下，然后解压.zip那个文件就可以了。

**Comment by yiyikkk** [comment]
好的好的，非常感谢~

**Comment by Kenny-Li2023** [comment]
> 上传的是只包含21类的子数据集。之前有其他做Hashing的作者用的是Matlab的.mat文件类型，我给转换成了Pytorch的数据格式保存。因为文件太大，百度云要分卷上传，每个卷最大4G。
> 你要是使用的话所有文件都要下载，保存在一个文件夹下，然后解压.zip那个文件就可以了。

请问你知道关于这21类的标签解释吗，我想知道每张图所对应的具体的标签

**Comment by TreezzZ** [comment]
> > 上传的是只包含21类的子数据集。之前有其他做Hashing的作者用的是Matlab的.mat文件类型，我给转换成了Pytorch的数据格式保存。因为文件太大，百度云要分卷上传，每个卷最大4G。
> > 你要是使用的话所有文件都要下载，保存在一个文件夹下，然后解压.zip那个文件就可以了。
> 
> 请问你知道关于这21类的标签解释吗，我想知道每张图所对应的具体的标签

我没有提取出的21类的标签解释，不过这个链接[https://lms.comp.nus.edu.sg/wp-content/uploads/2019/research/nuswide/ConceptsList.zip]里提供了完整的81类的标签。如果你想要得到21类标签的解释，需要：
1. 自己写个脚本，找出最多的21类
2. 根据这21类的index，在原始的81类标签里找到对应的文本解释即可
