### ISSUE TITLE
NUSWIDE数据集问题

### ISSUE THREAD

**Issue by chenshen03** [TreezzZ/DSDH_PyTorch#2]
请问下NUSWIDE数据集下，这两行的写法是不是有误？正确的写法应该是：
```python
query_index = perm_index[:num_query]
train_index = perm_index[num_query:num_query+num_train]
```
https://github.com/TreezzZ/DSDH_PyTorch/blob/4c1f5a07f1b0c91356204a1049b099146b3ead53/data/nus_wide.py#L70-L71

**Comment by TreezzZ** [comment]
是写错了，已修改，谢谢！

**Comment by TreezzZ** [comment]
> 请问下NUSWIDE数据集下，这两行的写法是不是有误？正确的写法应该是：
> 
> ```python
> query_index = perm_index[:num_query]
> train_index = perm_index[num_query:num_query+num_train]
> ```
> 
> https://github.com/TreezzZ/DSDH_PyTorch/blob/4c1f5a07f1b0c91356204a1049b099146b3ead53/data/nus_wide.py#L70-L71

是写错了，已修改，谢谢！
