### ISSUE TITLE
multi gpus training

### ISSUE THREAD

**Issue by mynameischaos** [TreezzZ/DSDH_PyTorch#3]
Environment: pytorch==1.1.0 torchvision==0.3.0 cudatoolkit=9.0
Problem:
I added  two lines: 
  model = nn.DataParalle(model)  
  model.to(device) after model = AlexNet(code_length) in alexnet.py, but I found it can not speed up the training, can you help me?

**Comment by TreezzZ** [comment]
1. 参考PyTorch官方教程https://pytorch.org/tutorials/intermediate/ddp_tutorial.html ，PyTorch1.0以后都建议使用DistributedDataParallel来做数据并行。
2. 使用Uber的Horovod库进行多GPU训练。

在运行python run.py这行命令的时候加上两个参数，指定多块GPU，不过记不清具体的命令了，建议去谷歌搜索。我在做多GPU训练的时候GPU0占用显存远大于其他GPU，造成显存不够训练中断，然后就放弃折腾多GPU了，如果需要加速训练，可以考虑用Nvidia-Dali库和Nvidia-APEX库，效果显著
